// <auto-generated />
using System;
using Car_services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_services.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260914193039_alldone")]
    partial class alldone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_services.Model.Car", b =>
                {
                    b.Property<string>("Licences_Plate")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Car_Company")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CurrentKM")
                        .HasColumnType("int");

                    b.Property<int>("Customer_Id")
                        .HasColumnType("int");

                    b.Property<string>("Engine_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fuel_Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("No_of_cylinders")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<double>("PriceInEgp")
                        .HasColumnType("float");

                    b.Property<DateOnly>("manufactuare_date")
                        .HasColumnType("date");

                    b.HasKey("Licences_Plate");

                    b.HasIndex("Customer_Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Car_services.Model.CarsForRent", b =>
                {
                    b.Property<string>("LicencePlate")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Car_Company")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Engine_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fuel_Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("No_of_cylinders")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<DateOnly>("manufactuare_date")
                        .HasColumnType("date");

                    b.HasKey("LicencePlate");

                    b.ToTable("CarsForRents");
                });

            modelBuilder.Entity("Car_services.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Full_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Car_services.Model.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<DateOnly>("StartWorkDate")
                        .HasColumnType("date");

                    b.HasKey("DriverId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Car_services.Model.EmergencyRequest", b =>
                {
                    b.Property<int>("EmergencyRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmergencyRequestId"));

                    b.Property<string>("Car_LicencePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmergenctTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmergencyRequestId");

                    b.HasIndex("Car_LicencePlate");

                    b.HasIndex("DriverId");

                    b.ToTable("EmergencyRequests");
                });

            modelBuilder.Entity("Car_services.Model.EmergencyTruck", b =>
                {
                    b.Property<string>("Licence_Plate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Manufactuare_Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TruckCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruckModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Licence_Plate");

                    b.HasIndex("BranchId");

                    b.HasIndex("DriverId");

                    b.ToTable("EmergencyTrucks");
                });

            modelBuilder.Entity("Car_services.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Facultly")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Full_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("Starting_work_date")
                        .HasColumnType("date");

                    b.Property<int>("Years_of_experince")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone_number")
                        .IsUnique();

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Car_services.Model.RentedCarCustomer", b =>
                {
                    b.Property<int>("RentedCarCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentedCarCustomerId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("LicencsePlateRented")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("No_ofDays_ForRent")
                        .HasColumnType("int");

                    b.Property<double>("PriceForRent")
                        .HasColumnType("float");

                    b.Property<DateOnly>("RentEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RentStartDate")
                        .HasColumnType("date");

                    b.HasKey("RentedCarCustomerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LicencsePlateRented");

                    b.ToTable("RentedCarCustomers");
                });

            modelBuilder.Entity("Car_services.Model.ServiceByKm", b =>
                {
                    b.Property<int>("ServiceByKmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceByKmId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KilometerInterval")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ServiceByKmId");

                    b.ToTable("ServiceByKm");
                });

            modelBuilder.Entity("Car_services.Model.service", b =>
                {
                    b.Property<int>("serviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serviceId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Service_Date")
                        .HasColumnType("date");

                    b.HasKey("serviceId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CarId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("service");
                });

            modelBuilder.Entity("Car_services.Model.service_branches", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Branch_location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Close_time")
                        .HasColumnType("time");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Open_time")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Opening_date")
                        .HasColumnType("date");

                    b.HasKey("BranchId");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.ToTable("service_branches");
                });

            modelBuilder.Entity("Car_services.Model.Car", b =>
                {
                    b.HasOne("Car_services.Model.Customer", "customer")
                        .WithMany("Cars")
                        .HasForeignKey("Customer_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("Car_services.Model.Driver", b =>
                {
                    b.HasOne("Car_services.Model.service_branches", "WorkingBranch")
                        .WithMany("Drivers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkingBranch");
                });

            modelBuilder.Entity("Car_services.Model.EmergencyRequest", b =>
                {
                    b.HasOne("Car_services.Model.Car", "CarRequest")
                        .WithMany("Requests")
                        .HasForeignKey("Car_LicencePlate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_services.Model.Driver", "Driver")
                        .WithMany("EmergencyRequests")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarRequest");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Car_services.Model.EmergencyTruck", b =>
                {
                    b.HasOne("Car_services.Model.service_branches", "Branch")
                        .WithMany("Trucks")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car_services.Model.Driver", "Driver")
                        .WithMany("TrucksDriven")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Car_services.Model.Employee", b =>
                {
                    b.HasOne("Car_services.Model.service_branches", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Car_services.Model.RentedCarCustomer", b =>
                {
                    b.HasOne("Car_services.Model.Customer", "CutomeRent")
                        .WithMany("CarsCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car_services.Model.CarsForRent", "CarRented")
                        .WithMany("CarsCutomers")
                        .HasForeignKey("LicencsePlateRented")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarRented");

                    b.Navigation("CutomeRent");
                });

            modelBuilder.Entity("Car_services.Model.service", b =>
                {
                    b.HasOne("Car_services.Model.service_branches", "Branch_of_service")
                        .WithMany("Services")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car_services.Model.Car", "LicensePlate")
                        .WithMany("Services")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car_services.Model.Employee", "Employeoe")
                        .WithMany("Services")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch_of_service");

                    b.Navigation("Employeoe");

                    b.Navigation("LicensePlate");
                });

            modelBuilder.Entity("Car_services.Model.service_branches", b =>
                {
                    b.HasOne("Car_services.Model.Employee", "Manager")
                        .WithOne("Manager_Branch")
                        .HasForeignKey("Car_services.Model.service_branches", "ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Car_services.Model.Car", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Car_services.Model.CarsForRent", b =>
                {
                    b.Navigation("CarsCutomers");
                });

            modelBuilder.Entity("Car_services.Model.Customer", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("CarsCustomers");
                });

            modelBuilder.Entity("Car_services.Model.Driver", b =>
                {
                    b.Navigation("EmergencyRequests");

                    b.Navigation("TrucksDriven");
                });

            modelBuilder.Entity("Car_services.Model.Employee", b =>
                {
                    b.Navigation("Manager_Branch");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Car_services.Model.service_branches", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Employees");

                    b.Navigation("Services");

                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
