// <auto-generated />
using System;
using Car_services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_services.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820165901_priceAdded")]
    partial class priceAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_services.Model.Car", b =>
                {
                    b.Property<string>("Licences_Plate")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Car_Company")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Customer_Id")
                        .HasColumnType("int");

                    b.Property<string>("Engine_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fuel_Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("No_of_cylinders")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<double>("PriceInEgp")
                        .HasColumnType("float");

                    b.Property<DateOnly>("manufactuare_date")
                        .HasColumnType("date");

                    b.HasKey("Licences_Plate");

                    b.HasIndex("Customer_Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Car_services.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Full_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Car_services.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Facultly")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Full_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("Starting_work_date")
                        .HasColumnType("date");

                    b.Property<int>("Years_of_experince")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone_number")
                        .IsUnique();

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Car_services.Model.service", b =>
                {
                    b.Property<int>("serviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serviceId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Service_Date")
                        .HasColumnType("date");

                    b.HasKey("serviceId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CarId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("service");
                });

            modelBuilder.Entity("Car_services.Model.service_branches", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Branch_location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Close_time")
                        .HasColumnType("time");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Open_time")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Opening_date")
                        .HasColumnType("date");

                    b.HasKey("BranchId");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.ToTable("service_branches");
                });

            modelBuilder.Entity("Car_services.Model.Car", b =>
                {
                    b.HasOne("Car_services.Model.Customer", "customer")
                        .WithMany("Cars")
                        .HasForeignKey("Customer_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("Car_services.Model.Employee", b =>
                {
                    b.HasOne("Car_services.Model.service_branches", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Car_services.Model.service", b =>
                {
                    b.HasOne("Car_services.Model.service_branches", "Branch_of_service")
                        .WithMany("Services")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car_services.Model.Car", "LicensePlate")
                        .WithMany("Services")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car_services.Model.Employee", "Employeoe")
                        .WithMany("Services")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch_of_service");

                    b.Navigation("Employeoe");

                    b.Navigation("LicensePlate");
                });

            modelBuilder.Entity("Car_services.Model.service_branches", b =>
                {
                    b.HasOne("Car_services.Model.Employee", "Manager")
                        .WithOne("Manager_Branch")
                        .HasForeignKey("Car_services.Model.service_branches", "ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Car_services.Model.Car", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Car_services.Model.Customer", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Car_services.Model.Employee", b =>
                {
                    b.Navigation("Manager_Branch");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Car_services.Model.service_branches", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
