// <auto-generated />
using System;
using CSMS.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSMS.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSMS.DAL.Models.BranchProduct", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.HasKey("BranchId", "ProductId");

                    b.HasIndex(new[] { "BranchId" }, "IX_BranchProduct_BranchId");

                    b.HasIndex(new[] { "ProductId" }, "IX_BranchProduct_ProductId");

                    b.ToTable("BranchProducts", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.Car", b =>
                {
                    b.Property<string>("LicencesPlate")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("Licences_Plate");

                    b.Property<string>("CarCompany")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("Car_Company");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CurrentKm")
                        .HasColumnType("int")
                        .HasColumnName("CurrentKM");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Engine_type");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Fuel_Type");

                    b.Property<DateOnly>("ManufactuareDate")
                        .HasColumnType("date")
                        .HasColumnName("manufactuare_date");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NoOfCylinders")
                        .HasColumnType("int")
                        .HasColumnName("No_of_cylinders");

                    b.Property<double>("PriceInEgp")
                        .HasColumnType("float");

                    b.HasKey("LicencesPlate");

                    b.HasIndex(new[] { "CustomerId" }, "IX_Car_Customer_Id");

                    b.ToTable("Car", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.CarsForRent", b =>
                {
                    b.Property<string>("LicencePlate")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("CarCompany")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("Car_Company");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Engine_type");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Fuel_Type");

                    b.Property<DateOnly>("ManufactuareDate")
                        .HasColumnType("date")
                        .HasColumnName("manufactuare_date");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NoOfCylinders")
                        .HasColumnType("int")
                        .HasColumnName("No_of_cylinders");

                    b.HasKey("LicencePlate");

                    b.ToTable("CarsForRents", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Full_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.HasIndex(new[] { "Email" }, "IX_Customer_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "IX_Customer_Phone")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<DateOnly>("StartWorkDate")
                        .HasColumnType("date");

                    b.HasKey("DriverId");

                    b.HasIndex(new[] { "BranchId" }, "IX_Drivers_BranchId");

                    b.HasIndex(new[] { "Email" }, "IX_Drivers_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "IX_Drivers_PhoneNumber")
                        .IsUnique();

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.EmergencyRequest", b =>
                {
                    b.Property<int>("EmergencyRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmergencyRequestId"));

                    b.Property<string>("CarLicencePlate")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("Car_LicencePlate");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmergenctTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmergencyRequestId");

                    b.HasIndex(new[] { "CarLicencePlate" }, "IX_EmergencyRequests_Car_LicencePlate");

                    b.HasIndex(new[] { "DriverId" }, "IX_EmergencyRequests_DriverId");

                    b.ToTable("EmergencyRequests", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.EmergencyTruck", b =>
                {
                    b.Property<string>("LicencePlate")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Licence_Plate");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("ManufactuareDate")
                        .HasColumnType("date")
                        .HasColumnName("Manufactuare_Date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TruckCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruckModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicencePlate");

                    b.HasIndex(new[] { "BranchId" }, "IX_EmergencyTrucks_BranchId");

                    b.HasIndex(new[] { "DriverId" }, "IX_EmergencyTrucks_DriverId");

                    b.ToTable("EmergencyTrucks", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Facultly")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Full_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Phone_number");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("salary");

                    b.Property<DateOnly>("StartingWorkDate")
                        .HasColumnType("date")
                        .HasColumnName("Starting_work_date");

                    b.Property<int>("YearsOfExperince")
                        .HasColumnType("int")
                        .HasColumnName("Years_of_experince");

                    b.HasKey("EmployeeId");

                    b.HasIndex(new[] { "BranchId" }, "IX_Employee_BranchId");

                    b.HasIndex(new[] { "Email" }, "IX_Employee_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "IX_Employee_Phone_number")
                        .IsUnique();

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.RentedCarCustomer", b =>
                {
                    b.Property<int>("RentedCarCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentedCarCustomerId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("LicencsePlateRented")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("NoOfDaysForRent")
                        .HasColumnType("int")
                        .HasColumnName("No_ofDays_ForRent");

                    b.Property<double>("PriceForRent")
                        .HasColumnType("float");

                    b.Property<DateOnly>("RentEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RentStartDate")
                        .HasColumnType("date");

                    b.HasKey("RentedCarCustomerId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_RentedCarCustomers_CustomerId");

                    b.HasIndex(new[] { "LicencsePlateRented" }, "IX_RentedCarCustomers_LicencsePlateRented");

                    b.ToTable("RentedCarCustomers", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VisitId");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.ServiceBranch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Branch_location");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Branch_name");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time")
                        .HasColumnName("Close_time");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time")
                        .HasColumnName("Open_time");

                    b.Property<DateOnly>("OpeningDate")
                        .HasColumnType("date")
                        .HasColumnName("Opening_date");

                    b.HasKey("BranchId");

                    b.HasIndex(new[] { "ManagerId" }, "IX_service_branches_ManagerId")
                        .IsUnique()
                        .HasFilter("([ManagerId] IS NOT NULL)");

                    b.ToTable("service_branches", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.ServiceByKm", b =>
                {
                    b.Property<int>("ServiceByKmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceByKmId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KilometerInterval")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ServiceByKmId");

                    b.ToTable("ServiceByKm", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.ServiceByKmProduct", b =>
                {
                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("serviceByKmId")
                        .HasColumnType("int");

                    b.HasKey("productId", "serviceByKmId");

                    b.HasIndex("serviceByKmId");

                    b.ToTable("ServiceByKmProducts", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VisitId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("Service_Date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitId");

                    b.HasIndex(new[] { "BranchId" }, "IX_service_BranchId");

                    b.HasIndex(new[] { "CarId" }, "IX_service_CarId");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_service_EmployeeId");

                    b.ToTable("Visit", (string)null);
                });

            modelBuilder.Entity("CSMS.DAL.Models.BranchProduct", b =>
                {
                    b.HasOne("CSMS.DAL.Models.ServiceBranch", "Branch")
                        .WithMany("branchProducts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSMS.DAL.Models.Product", "Product")
                        .WithMany("branchProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CSMS.DAL.Models.Car", b =>
                {
                    b.HasOne("CSMS.DAL.Models.Customer", "Customer")
                        .WithMany("Cars")
                        .HasForeignKey("CustomerId")
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CSMS.DAL.Models.Driver", b =>
                {
                    b.HasOne("CSMS.DAL.Models.ServiceBranch", "Branch")
                        .WithMany("Drivers")
                        .HasForeignKey("BranchId")
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CSMS.DAL.Models.EmergencyRequest", b =>
                {
                    b.HasOne("CSMS.DAL.Models.Car", "CarLicencePlateNavigation")
                        .WithMany("EmergencyRequests")
                        .HasForeignKey("CarLicencePlate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSMS.DAL.Models.Driver", "Driver")
                        .WithMany("EmergencyRequests")
                        .HasForeignKey("DriverId")
                        .IsRequired();

                    b.Navigation("CarLicencePlateNavigation");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("CSMS.DAL.Models.EmergencyTruck", b =>
                {
                    b.HasOne("CSMS.DAL.Models.ServiceBranch", "Branch")
                        .WithMany("EmergencyTrucks")
                        .HasForeignKey("BranchId")
                        .IsRequired();

                    b.HasOne("CSMS.DAL.Models.Driver", "Driver")
                        .WithMany("EmergencyTrucks")
                        .HasForeignKey("DriverId")
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("CSMS.DAL.Models.Employee", b =>
                {
                    b.HasOne("CSMS.DAL.Models.ServiceBranch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CSMS.DAL.Models.RentedCarCustomer", b =>
                {
                    b.HasOne("CSMS.DAL.Models.Customer", "Customer")
                        .WithMany("RentedCarCustomers")
                        .HasForeignKey("CustomerId")
                        .IsRequired();

                    b.HasOne("CSMS.DAL.Models.CarsForRent", "LicencsePlateRentedNavigation")
                        .WithMany("RentedCarCustomers")
                        .HasForeignKey("LicencsePlateRented")
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LicencsePlateRentedNavigation");
                });

            modelBuilder.Entity("CSMS.DAL.Models.Service", b =>
                {
                    b.HasOne("CSMS.DAL.Models.Product", "Product")
                        .WithMany("services")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSMS.DAL.Models.Visit", "Visit")
                        .WithMany("Services")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CSMS.DAL.Models.ServiceBranch", b =>
                {
                    b.HasOne("CSMS.DAL.Models.Employee", "Manager")
                        .WithOne("ServiceBranch")
                        .HasForeignKey("CSMS.DAL.Models.ServiceBranch", "ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CSMS.DAL.Models.ServiceByKmProduct", b =>
                {
                    b.HasOne("CSMS.DAL.Models.Product", "product")
                        .WithMany("serviceByKmProducts")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSMS.DAL.Models.ServiceByKm", "serviceByKm")
                        .WithMany("serviceByKmProducts")
                        .HasForeignKey("serviceByKmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("serviceByKm");
                });

            modelBuilder.Entity("CSMS.DAL.Models.Visit", b =>
                {
                    b.HasOne("CSMS.DAL.Models.ServiceBranch", "Branch")
                        .WithMany("Services")
                        .HasForeignKey("BranchId")
                        .IsRequired();

                    b.HasOne("CSMS.DAL.Models.Car", "Car")
                        .WithMany("Services")
                        .HasForeignKey("CarId")
                        .IsRequired();

                    b.HasOne("CSMS.DAL.Models.Employee", "Employee")
                        .WithMany("Services")
                        .HasForeignKey("EmployeeId")
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Car");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CSMS.DAL.Models.Car", b =>
                {
                    b.Navigation("EmergencyRequests");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("CSMS.DAL.Models.CarsForRent", b =>
                {
                    b.Navigation("RentedCarCustomers");
                });

            modelBuilder.Entity("CSMS.DAL.Models.Customer", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("RentedCarCustomers");
                });

            modelBuilder.Entity("CSMS.DAL.Models.Driver", b =>
                {
                    b.Navigation("EmergencyRequests");

                    b.Navigation("EmergencyTrucks");
                });

            modelBuilder.Entity("CSMS.DAL.Models.Employee", b =>
                {
                    b.Navigation("ServiceBranch");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("CSMS.DAL.Models.Product", b =>
                {
                    b.Navigation("branchProducts");

                    b.Navigation("serviceByKmProducts");

                    b.Navigation("services");
                });

            modelBuilder.Entity("CSMS.DAL.Models.ServiceBranch", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("EmergencyTrucks");

                    b.Navigation("Employees");

                    b.Navigation("Services");

                    b.Navigation("branchProducts");
                });

            modelBuilder.Entity("CSMS.DAL.Models.ServiceByKm", b =>
                {
                    b.Navigation("serviceByKmProducts");
                });

            modelBuilder.Entity("CSMS.DAL.Models.Visit", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
